name: btp-setup-automator - CAP app
# This file defines a workflow that calls the btp-setup-automator and deploys a
# use case around deploying a CAP app

on:
  workflow_dispatch:
    inputs:
      GLOBALACCOUNT:
        description: "Your Global account subdomain"
        required: true
      REGION:
        description: "Region for the sub account"
        default: "us10"
        required: true

env:
  DIRECTORY_NAME: Tests btp-setup-automator
  SUBACCOUNT_NAME: CAP app

  LOGIN_METHOD: envVariables
  # Don't change this value (folder created by GitHub automatically within Docker container)!
  FOLDER_REPO: /__w/

jobs:
  deploy-all-necessary-services:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sap-samples/btp-setup-automator-dev:dev
      options: --user root
    env:
      BTPSA_PARAM_MYPASSWORD: ${{ secrets.BTPSA_PARAM_MYPASSWORD }}
      BTPSA_PARAM_MYEMAIL: ${{ secrets.BTPSA_PARAM_MYEMAIL }}
      BTPSA_PARAM_GLOBALACCOUNT: ${{ github.event.inputs.GLOBALACCOUNT }}
      BTPSA_PARAM_IDP_TENANT: ${{ github.event.inputs.IDP_TENANT }}
      BTPSA_PARAM_IDP_TENANT_CFG_NAME: ${{ github.event.inputs.IDP_TENANT_CFG_NAME }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: "Get repo folder in container"
        working-directory: /home/user
        shell: bash
        run: |
          echo "REPO_NAME=/__w/$(basename ${{ github.repository }})/$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: "Setup account and deploy CAP app"
        working-directory: /home/user
        shell: bash
        run: |
          ./btpsa \
          -parameterfile '${{ env.REPO_NAME }}/btpsa_session/cap_app/generic_parameters.json' \
          -globalaccount '${{ github.event.inputs.GLOBALACCOUNT }}' \
          -subaccountname '${{ env.SUBACCOUNT_NAME }}' \
          -region '${{ github.event.inputs.REGION }}' \
          -directoryname '${{ env.DIRECTORY_NAME }}' \
          -loginmethod '${{ env.LOGIN_METHOD }}' \
          -usedirectory true
